version: 2
jobs:
  ensure_branch:
    docker:
      - image: skywayci/skyway-js-sdk
    steps:
      - checkout
      - run:
          name: Install extra deps for CI
          command: npm install --no-save @octokit/rest@16.36.0
      - run: node ./scripts/ensure-branch

  test:
    docker:
      - image: skywayci/skyway-js-sdk
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  release_staging:
    docker:
      - image: skywayci/skyway-js-sdk
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install extra deps for CI
          command: npm install --no-save replace-in-file@3.0.0 aws-sdk@2.597.0
      - run: node ./scripts/release-staging

  release_master:
    docker:
      - image: skywayci/skyway-js-sdk
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install extra deps for CI
          command: npm install --no-save replace-in-file@3.0.0 aws-sdk@2.597.0 @octokit/rest@16.36.0 @slack/client@5.0.2
      - add_ssh_keys:
          fingerprints:
            - "56:a2:ef:d1:41:dd:99:a2:95:cf:df:a0:15:0e:6b:f1"
      - run: node ./scripts/release-master

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - ensure_branch
      - test:
          requires:
            - ensure_branch
      - release_staging:
          requires:
            - test
          filters:
            branches:
              only: staging
      - release_master:
          requires:
            - test
          filters:
            branches:
              only: master
